version: '3'
volumes:
  websocket_config:
  core_db:
  core_cache:
  redis_data:
  core_composer_cache:
  website_composer_cache:
  website_nginx_logs:
  
services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    restart: always
    volumes:
      - .:/app/:z
    links: 
      - core-db
    networks:
      ftcbot:
#    command: sh
    
  front-server:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
    links: 
      - website
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:z
      - ./public:/app/public:z
      - website_nginx_logs:/var/log/nginx
    networks:
      ftcbot:

    
  core:
#    image: qbonaventure/discord-bot-core
    image: qbonaventure/discord-bot-core
    tty: true
#    restart: always
    env_file:
      - .env
    links:
      - websocket
      - core-db
    volumes:
      - core_composer_cache:/app/vendor
    networks:
      ftcbot:
      
#  core-ui-server:
#      image: nginx:alpine
#      links:
#          - core
#      networks:
#          ftcbot:
#      ports:
#          - "64578:80"
#          - "64579:443"
#      volumes:
#          - ./public/assets:/app/public/assets:z
#          - ./ui-nginx.conf:/etc/nginx/conf.d/default.conf:z
#          - /tmp/botlogs/nginx:/var/log/nginx:z
      
  core-db:
    image: postgres:10-alpine
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: discord_bot
    volumes:
      - core_db:/var/lib/postgresql/data:z
    networks:
      ftcbot:
      
  core-cache:
    image: redis:alpine
    expose:
      - "6379"
    volumes:
      - core_cache:/data:z
    networks:
      ftcbot:

  websocket:
    image: qbonaventure/discord-bot-ws
    expose:
      - "7632"
    tty: true
    restart: always
    volumes:
      - ./config:/app/config:z
    links: 
      - broker
      - cache
    networks:
      ftcbot:
      
  broker:
    image: rabbitmq:3.7-alpine
    expose:
      - "4369"
      - "5671"
      - "5672"
      - "25672"
    networks:
      ftcbot:
      
  cache:
    image: redis:alpine
    expose:
      - "6379"
    volumes:
      - redis_data:/data:z
    networks:
      ftcbot:
      
networks:
    ftcbot:
        driver: bridge

