version: '3.6'

volumes:
  websocket_config:
  core_db:
  core_cache:
  redis_data:
  core_composer_cache:
  ws_composer_cache:
  website_composer_cache:
  website_nginx_logs:
  website_cache_data:
  
services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    restart: always
    external_links:
      - core-db
    env_file:
      - .env
    expose:
      - "9000"
    secrets:
      - ftcbot-db-password
      - ftcbot-db-user
      - ftcbot-broker-password
      - ftcbot-broker-username
      - ftcbot-discord-auth-token
      - ftcbot-discord-token
      - ftcbot-website-session-key
    volumes:
      - .:/app/:z
      - .composer/auth.json:/root/.composer/auth.json
    extra_hosts:
      - "discord-oauth.fearthec.test:172.24.0.2"
    networks:
      ftcbot_dev:
      traefik:
    
  front-server:
    image: qbonaventure/discord-website-server:1
    volumes:
      - .:/app:z
      - website_nginx_logs:/var/log/nginx
    labels:
      traefik.enable: true
      traefik.backend: discord_website
      traefik.frontend.rule: HostRegexp:{subdomain:.+}.ftcbot-dev.test
      traefik.frontend.priority: 1
      traefik.docker.network: traefik
      traefik.port: 80
    networks:
      ftcbot_dev:
      traefik:

  website-cache:
    image: redis:alpine
    expose:
      - "6379"
    volumes:
      - website_cache_data:/data:z
    networks:
      ftcbot_dev:
      
      
secrets:
  ftcbot-db-password:
    file: /var/docker-secrets/ftcbot/dev/ftcbot-db-password
  ftcbot-db-user:
    file: /var/docker-secrets/ftcbot/dev/ftcbot-db-user
  ftcbot-broker-password:
    file: /var/docker-secrets/ftcbot/dev/ftcbot-broker-password
  ftcbot-broker-username:
    file: /var/docker-secrets/ftcbot/dev/ftcbot-broker-username
  ftcbot-discord-auth-token:
    file: /var/docker-secrets/ftcbot/dev/ftcbot-discord-auth-token
  ftcbot-discord-token:
    file: /var/docker-secrets/ftcbot/dev/ftcbot-discord-token
  ftcbot-website-session-key:
    file: /var/docker-secrets/ftcbot/dev/ftcbot-website-session-key    
    
networks:
  ftcbot_dev:
    external: true
  traefik:
    external: true
