version: '3.3'
volumes:
  website_composer_cache:
  website_nginx_logs:
  website_public_volume:
  
services:
  website:
#    image: qbonaventure/discord-bot-website:latest
    image: discord-bot-website-test
    tty: true
    restart: always
    env_file:
      - .env
    volumes:
      - website_composer_cache:/app/vendor
      - website_public_volume:/app/public
    deploy:
      labels :
        ftcbot.service: core
      replicas: 1
      update_config:
        parallelism: 2
        delay: 20s
      restart_policy:
        condition: on-failure
    networks:
      ftcbot:
      
  traefik:
    image: traefik
    command: -c /dev/null --api --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8081:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role==manager]
    
  front-server:
    image: qbonaventure/discord-website-server:1
    ports:
      - "7612:80"
    links: 
      - website
    volumes:
      - website_nginx_logs:/var/log/nginx
      - website_public_volume:/app/public
    deploy:
      labels:
        ftcbot.service: website-front-server
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      ftcbot:

      
networks:
  ftcbot:

