version: '3.3'
volumes:
  website_composer_cache:
  website_nginx_logs:
  website_public_volume:
  
services:
  website:
    image: qbonaventure/discord-bot-website:latest
    tty: true
    restart: always
    env_file:
      - .env
    volumes:
      - website_composer_cache:/app/vendor
      - website_public_volume:/app/public
    deploy:
      labels :
        ftcbot.service: core
      replicas: 1
      update_config:
        parallelism: 2
        delay: 20s
      restart_policy:
        condition: on-failure
    networks:
      ftcbot:
    
  front-server:
    image: nginx-test
#    image: qbonaventure/discord-website-server:1
    ports:
      - "7612:80"
    links: 
      - website
    volumes:
      - website_nginx_logs:/var/log/nginx
      - website_public_volume:/app/public
    deploy:
      labels:
        ftcbot.service: website-front-server
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      ftcbot:

      
networks:
  ftcbot:

