version: '3.6'

volumes:
  websocket_config:
  core_db:
  core_cache:
  redis_data:
  core_composer_cache:
  ws_composer_cache:
  website_composer_cache:
  website_nginx_logs:
  
services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    restart: always
    external_links:
      - core-db
    env_file:
      - .env
    expose:
      - "9000"
    volumes:
      - .:/app/:z
    networks:
      ftcbot_dev:
    
  front-server:
    image: qbonaventure/discord-website-server:1
    ports:
      - "7610:80"
    volumes:
      - .:/app:z
      - website_nginx_logs:/var/log/nginx
    labels:
      traefik.enable: true
      traefik.backend: discord_website
      traefik.frontend.rule: Host:ftcbot-dev.test
      traefik.docker.network: traefik
      traefik.port: 80
    networks:
      ftcbot_dev:
      traefik:

      
networks:
  ftcbot_dev:
    external: true
  traefik:
    external: true
