version: '3.3'
volumes:
  website_composer_cache:
  website_nginx_logs:
  
services:
  website:
    image: qbonaventure/discord-bot-website:latest
    tty: true
    restart: always
    env_file:
      - .env
    volumes:
      - website_composer_cache:/app/vendor
    deploy:
      labels :
        ftcbot.service: core
      replicas: 1
      update_config:
        parallelism: 2
        delay: 20s
      restart_policy:
        condition: on-failure
    networks:
      ftcbot:
    
  front-server:
    image: nginx:1.15-alpine
    ports:
      - "7612:80"
      - "7613:443"
    links: 
      - website
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:z
      - ./public:/app/public:z
      - website_nginx_logs:/var/log/nginx
    deploy:
      labels:
        ftcbot.service: website-front-server
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      ftcbot:

      
networks:
  ftcbot:

