<?php $this->layout('layout::default'); ?>

<?php $this->push('stylesheets'); ?>
	<link rel="stylesheet" type="text/css" href="/stylesheets/admin.css" />
<?php $this->end(); ?>


<nav>
	<a href="<?= $this->url('admin.roles', ['roleId' => null]); ?>">
		Roles
	</a>
	<a href="<?= $this->url('admin.members', ['memberId' => null]); ?>">
		Members
	</a>
	<a href="<?= $this->url('admin.channels', ['channelId' => null]); ?>">
		Channels
	</a>
	<a href="<?= $this->url('admin.rbac'); ?>">
		RBAC
	</a>
</nav>

<?= $this->section('content') ?>