<?php $this->layout('layout::default', ['title' => '403 Unauthorized']) ?>

<h1>Oops!</h1>
<p>You don't have access to this page !</p>

<?php if ($user['user_id']): ?>
    <p>
	    Let's <a href="<?= $oauthServerUri ?>">login</a> or back to the <?php if($this->e($previousUrl)): echo '<a href="'.$previousUrl.'">previous page</a> you were visiting, or maybe the'; endif; ?> <a href="/">Home Page</a>.
    </p>
<?php else: ?>
	<p>
		Please <a href="<?= $oauthServerUri ?>">login</a> !</p>
	<p>
<?php endif; ?>