<?php $this->layout('layout::error', ['title' => '403 Unauthorized']) ?>

<h1>Oops! This wonderful world isn't built yet... or has been destroyed!</h1>


<?php if ($user['user_id']): ?>
    <p>
	    Let's <a href="<?= $oauthServerUri ?>">login</a> or back to the <?php if($this->e($previousUrl)): echo '<a href="'.$previousUrl.'">previous page</a> you were visiting, or maybe the'; endif; ?> <a href="/">Home Page</a>.
    </p>
<?php else: ?>
	<p>
		If you think your one of the chosen few that may walk this land, please <a href="<?= $oauthServerUri ?>">login</a> !</p>
	<p>
<?php endif; ?>