<?php

declare(strict_types=1);

use FTC\Discord\Model\Aggregate\Guild;

/**
 * @var Guild $guildInfo
 */
?>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>Not Found</title>
    <link rel="shortcut icon" href="assets/ico/favicon.ico" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet" />
    <style>
        body { padding-top: 70px; }
        .app { min-height: 100vh; }
        .app-footer { padding-bottom: 1em; }
        .zf-green, h2 a { color: #68b604; }
    </style>
    <?=$this->section('stylesheets')?>
</head>
<body class="app">
    <h1>Broken matchmaking... No guild uses this domain name !</h1>
</body>
</html>